## Element wise operations:

In [40]:
import numpy as np

In [41]:
x1 = np.array([2,-1,4])
x2 = np.array([1,2,3])

In [42]:
x1 + x2

array([3, 1, 7])

In [43]:
np.maximum(x1,0)

array([2, 0, 4])

In [44]:
np.minimum(x2,1)

array([1, 1, 1])

## Broadcasting:

In [45]:
x1 + 2 # broadcasting scalar 2 to each element of  vector x1

array([4, 1, 6])

In [46]:
x3 = np.array([[1,1,1],[2,2,2]])
x3

array([[1, 1, 1],
       [2, 2, 2]])

In [47]:
x3 + 2

array([[3, 3, 3],
       [4, 4, 4]])

In [48]:
x4 = np.array([-1,2,-1])

In [49]:
x3 + x4 

array([[0, 3, 0],
       [1, 4, 1]])

## Dot Product (matrix mul):


In [50]:
x1

array([ 2, -1,  4])

In [51]:
np.dot(x1,x1)

21

In [52]:
np.dot(x1,x1.T)

21

In [53]:
x3

array([[1, 1, 1],
       [2, 2, 2]])

In [54]:
x4

array([-1,  2, -1])

In [55]:
np.dot(x3,x4.T)

array([0, 0])

In [56]:
np.dot(x3,x3)  # error

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [57]:
np.dot(x3,x3.T)

array([[ 3,  6],
       [ 6, 12]])

In [58]:
x5 = np.array([[1,1],[2,2],[3,4]])
x6 = np.array([[1,2,3],[3,2,1]])

In [59]:
print(x5.shape)
print(x6.shape)

(3, 2)
(2, 3)


In [60]:
np.dot(x5,x6)

array([[ 4,  4,  4],
       [ 8,  8,  8],
       [15, 14, 13]])

In [61]:
np.dot(x5,x6.T) # error

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

## Reshaping:

In [62]:
x3

array([[1, 1, 1],
       [2, 2, 2]])

In [63]:
x3.shape

(2, 3)

In [64]:
x3.reshape(-1,1)

array([[1],
       [1],
       [1],
       [2],
       [2],
       [2]])

In [65]:
x3.reshape(1,-1)

array([[1, 1, 1, 2, 2, 2]])

In [66]:
x3.reshape(3,2)

array([[1, 1],
       [1, 2],
       [2, 2]])

In [67]:
x3.ravel()

array([1, 1, 1, 2, 2, 2])

In [68]:
x1.ravel()

array([ 2, -1,  4])

In [69]:
x4.ravel()

array([-1,  2, -1])

In [70]:
x5.ravel()

array([1, 1, 2, 2, 3, 4])

In [71]:
x5.ndim

2

In [72]:
x6.ndim

2

In [73]:
x5.shape

(3, 2)

In [74]:
x6.shape

(2, 3)

In [75]:
x6.dtype

dtype('int32')